### ISSUE TITLE
12. Reconstructing Networking Layer

### ISSUE THREAD

**Issue by Mintri1199** [MakeSchool-Tutorials/Product-Hunt-API-Tutorial#2]
In the instruction for making the getParams function, `case .comments(postId)` gave a Unresolved Identifier error. The solution I found was putting a `let` in the parameter 
ex: `case .comments(let postId)`

**Comment by Mintri1199** [comment]
> In the instruction for making the getParams function, `case .comments(postId)` gave a Unresolved Identifier error. The solution I found was putting a `let` in the parameter
> ex: `case .comments(let postId)`

Woops I didn't see the `let` before the `.comments`

**Comment by ibirnam** [comment]
All good! In the future if it turns out the issue you opened wasn't actually an issue, please close the issue yourself. Thanks!
