### ISSUE TITLE
How do I get all the posts through the API? Now can only get 50？

### ISSUE THREAD

**Issue by diegobona** [MakeSchool-Tutorials/Product-Hunt-API-Tutorial#3]
I Use：https://api.producthunt.com/v1/posts/all?sort_by=votes_count&order=desc

**Comment by amelinagzz** [comment]
This endpoint works better for that scenario: https://api.producthunt.com/v1/docs/posts/posts_all_keyset_pagination_(faster_recommended)
And since it uses pagination you can call it when you reach the end of the table to fetch the next set of posts.
